### ISSUE TITLE
Introduce semantic release for automated releases on npmjs.org

### ISSUE THREAD

**Issue by maoo** [finos/legend-studio#10]
Assuming that the Node logic that part of legend-studio must be consumed from GS as NPM package, we need to define a release process.

By introducing semantic-release, it will be possible to instrument release cycles and automated version updates based on git comment conventions; checkout https://github.com/semantic-release/semantic-release . We used it in the past for other hosted projects and it's quite powerful, but relies on precise git comments.

I'm happy to support this activity and integrate it into GitHub Actions.

**Comment by akphi** [comment]
FYI, we will use https://github.com/atlassian/changesets to manage our release process in Studio.
