### ISSUE TITLE
Bug: `yarn dev:sass` is generating untracked `.css`

### ISSUE THREAD

**Issue by MauricioUyaguari** [finos/legend-studio#1007]
### Similar issues

- [X] I have searched and found no existing similar issues

### How are you using Studio?

Legend Studio

### Current and expected behavior

setup scrip produces extra .css files

### Steps to reproduce

- Run `yarn workspace @finos/legend-studio dev:sass`
- build will succeed but will produce extra files
![image](https://user-images.githubusercontent.com/29690824/160698600-1e106279-36b9-4c9c-bc4b-c789515af2cd.png)

### Environment

```text
windows
```

### Contribution

- [ ] I would like to work on the fix for this issue

**Comment by akphi** [comment]
Actually the problem is with `dev:sass` script on both Mac and Windows.
