### ISSUE TITLE
Feature request: Enhance visual representation of dropdown of SchemaSpecification in `JsonSchemaConfiguration`

### ISSUE THREAD

**Issue by gayathrir11** [finos/legend-studio#1027]
### Similar requests

- [X] I have searched and found no existing similar requests

### How are you using Studio?

Legend Studio

### What problems are you trying to solve?

When you generate JsonSchemaSpecification from file generation and try to select SchemaSpecification from the dropdown it is kind of hard to see the dropdown as both the dropdown and the background is black in color
![image](https://user-images.githubusercontent.com/87973126/161575978-fc1449ab-d797-4378-98bf-7c86122349c2.png)

***Model Data***
```
###FileGeneration
JsonSchema test::file
{
  scopeElements: [test];
}


###GenerationSpecification
GenerationSpecification test::MyGenerationSpecification
{
  fileGenerations: [
    test::file
  ];
}


###Pure
Class test::class
{
  name: String[1];
  id: Integer[1];
}
```
Open file from form mode and try to click on dropdown for SchemaSpecification

### Describe the solution you would like to see implemented

Change the color of the dropdown to easily see it.

### Contribution

- [ ] I would like to work on this feature

**Comment by akphi** [comment]
I'm not sure I follow what you mean by the background hard to see here, but if you meant the bug where the dropdown push the bottom of the app to leave the empty space, this should be fixed by https://github.com/finos/legend-studio/issues/615 so closing this issue for now
