### ISSUE TITLE
Legend Studio: java.lang.NoSuchMethodError when gitlab oauth is configured

### ISSUE THREAD

**Issue by claudiubelu** [finos/legend-studio#1028]
### Similar issues

- [X] I have searched and found no existing similar issues

### How are you using Studio?

Legend Studio, Docker images (e.g. finos/legend-studio)

### Current and expected behavior

When using Legend Studio with any version newer than 3.6.0 from dockerhub, an ``java.lang.NoSuchMethodError`` error is encoutered every time when gitlab oauth is configured. The exception also causes the request to hang indefinitely. This issue does not occur when ``finos/legend-studio:3.4.0`` is used.

Logs: https://paste.ubuntu.com/p/pTYGSNrvmK/
http-config.json: https://paste.ubuntu.com/p/dmyHSzbKGw/
ui-config.json: https://paste.ubuntu.com/p/CGsRnRHQNH/
Sample job in which a request to Legend Studio hangs: https://github.com/claudiubelu/legend-juju-bundle/runs/5758396932?check_suite_focus=true

### Steps to reproduce

- Pull any Legend Studio image newer than 3.4.0 (e.g.: docker pull ``finos/legend-studio:4.10.0``)
- Run the docker image locally, and add the above files to it.
- Make a request to Legend Studio: curl ``http://container_ip:8080/studio``
- The request should now hang, and the errors above can be observed in Legend Studio

### Model data

```text
N/A
```

### Environment

```text
Any containerized environment.
```

### Contribution

- [ ] I would like to work on the fix for this issue

**Comment by akphi** [comment]
We can reproduce this error. So the problem seems to start appearing at `3.5.0` right? This is when we start using `finos/legend-shared-server@0.19.0` in our `Dockerfile` for Studio. We will be looking into this, but if you could help out with debugging, I'm happy to give you some pointers.

**Comment by akphi** [comment]
Hi, @epsstan has kindly did some digging and identified the root cause for us, let's track it at https://github.com/finos/legend-studio/issues/1073 instead.
