### ISSUE TITLE
Bug: Graph modifiers not working in editors post `mobx` refactoring

### ISSUE THREAD

**Issue by akphi** [finos/legend-studio#1037]
### Similar issues

- [X] I have searched and found no existing similar issues

### How are you using Studio?

Legend Studio, Legend Query

### Current and expected behavior

This is expected and caused by #1000 
We're dealing with the spots here

- [x] Query Builder
  - [x] Parameter
  - [x] Value Specification Editor
  - [x] Add projection, etc.
  - [x] Filter, etc.
  - [x] Post-filter
  - [x] Derivation
  - [x] Graph Fetch
  - [x] SubType
  - [x] exists()
- [x] UML editor
  - [x] Profile
  - [x] Enumeration
  - [x] Class
  - [x] Association
  - [x] Function
- [x] Text
- [x] Diagram editor
  - [x] DnD
- [x] File Generation
- [x] Generation Spec
- [x] Binding/Schema Set
- [x] Connection editor
  - [x] Model Connection
  - [x] FlatData
  - [x] Relational
- [x] Runtime editor
- [x] Service editor
  - [x] Execution
  - [x] Test
- [x] Mapping editor
  - [x] Operation
  - [x] Pure
  - [x] Relational
  - [x] FlatData
  - [x] Enumeration
  - [x] Mapping test
- [x] Studio app
  - [x] Create element
  - [x] Create package
  - [x] Delete element
  - [x] Rename element
- [x] Database
- [x] FlatData Store
- [x] Dataspace

### Environment

```text
N/A
```

### Contribution

- [ ] I would like to work on the fix for this issue

**Comment by YannanGao-gs** [comment]
Bugs expected and caused by https://github.com/finos/legend-studio/pull/1000 in @finos/legend-studio@5.1.4 : https://github.com/finos/legend-studio/issues/1050

**Comment by akphi** [comment]
> Bugs related to this found in query builder
> 
> * [ ]  Query builder's Derived Property name can't be reset by clicking the 'reset icon'
> 
> <img alt="bug1" width="1463" src="https://user-images.githubusercontent.com/73408381/162840457-689ada2f-4804-46ae-8b77-4c1dd26486dd.png">
> 
> * [ ]  Query builder's parameter can't be switched to a new type by selecting an option in the dropdown
> 
> <img alt="bug2" width="600" src="https://user-images.githubusercontent.com/73408381/162840578-b19cbd10-215c-4dcd-9694-b6a2b9ca77bd.png">
> 
> * [ ]  Fail to update lower bound of multiplicity for parameter in Query builder
> 
> <img alt="bug3" width="581" src="https://user-images.githubusercontent.com/73408381/162840636-f5cd9405-21f0-449d-89b3-3a758cab1756.png">

All of these have been addressed in #1049

**Comment by akphi** [comment]
After preliminary testing, I think we can close this issues. Any issues coming out of #1000 from this point one will be filed as separate bug.
