### ISSUE TITLE
Bug: Bugs From @finos/legend-studio@5.1.4

### ISSUE THREAD

**Issue by YannanGao-gs** [finos/legend-studio#1050]
### Similar issues

- [X] I have searched and found no existing similar issues

### How are you using Studio?

Legend Studio, Legend Query

### Current and expected behavior

Bugs to be fixed

- [ ] Query builder's Derived Property name can't be reset by clicking the 'reset icon'
<img width="1463" alt="bug1" src="https://user-images.githubusercontent.com/73408381/162840457-689ada2f-4804-46ae-8b77-4c1dd26486dd.png">

- [ ] Query builder's parameter can't be switched to a new type by selecting an option in the dropdown
<img width="600" alt="bug2" src="https://user-images.githubusercontent.com/73408381/162840578-b19cbd10-215c-4dcd-9694-b6a2b9ca77bd.png">

- [ ] Fail to update lower bound of multiplicity for parameter in Query builder
<img width="581" alt="bug3" src="https://user-images.githubusercontent.com/73408381/162840636-f5cd9405-21f0-449d-89b3-3a758cab1756.png">

### Environment

```text
System:
    OS: macOS 12.3.1
Browsers:
    Chrome: 100.0.4896.75
```

### Contribution

- [ ] I would like to work on the fix for this issue

**Comment by akphi** [comment]
@YannanGao-gs let's update the title, when did we publish `5.1.4` 😛

**Comment by akphi** [comment]
@YannanGao-gs could you merge this with the mega-thread https://github.com/finos/legend-studio/issues/1037. Thanks!
