### ISSUE TITLE
Bug: Fail to render valueSpecificationEditor for Date parameter of DerivedProperty in Query Builder

### ISSUE THREAD

**Issue by YannanGao-gs** [finos/legend-studio#1099]
### Similar issues

- [X] I have searched and found no existing similar issues

### How are you using Studio?

Legend Query

### Current and expected behavior

https://user-images.githubusercontent.com/73408381/164557302-db0a8c6e-f4d9-4a2b-9547-59b9a2aa28fb.mov

- [x]  mobx warning: [MobX: Since strict-mode is enabled, changing (observed) observable values without using an action is not allowed]
- [x] Fail to render the QueryBuilderValueSpecificationEditor for Date parameters of DerivedProperty the first time when we open the query builder
- [x] Fail to reset the QueryBuilderValueSpecificationEditor for Date to its original status
- [x]  Fail to reset the Enum param value

### Environment

```text
Chrome
```

### Contribution

- [X] I would like to work on the fix for this issue

**Comment by akphi** [comment]
@YannanGao-gs wrong tag, we should use `Component: Query Builder` instead
