### ISSUE TITLE
Bug: Fail to switch milestoning parameter type in Query Builder

### ISSUE THREAD

**Issue by YannanGao-gs** [finos/legend-studio#1106]
### Similar issues

- [X] I have searched and found no existing similar issues

### How are you using Studio?

Legend Query

### Current and expected behavior

https://user-images.githubusercontent.com/73408381/165148270-e89259ab-5e1c-4711-96bf-12ecd310332e.mov

### Environment

```text
Chrome
```

### Contribution

- [X] I would like to work on the fix for this issue

**Comment by akphi** [comment]
@YannanGao-gs Should we let @gayathrir11 take a look at this instead, as it might be due to #1000
