### ISSUE TITLE
Disable recursive viewing of parent class in explorer tree of query builder for better user experience

### ISSUE THREAD

**Issue by gayathrir11** [finos/legend-studio#1172]
### Similar issues

- [X] I have searched and found no existing similar issues

### How are you using Studio?

Legend Studio

### Current and expected behavior

We see the parent class recursively in the explorer tree of query builder

![Capture](https://user-images.githubusercontent.com/87973126/169257076-609b7877-6cbd-4a0d-91e8-0e36e2479d6c.PNG)

### Steps to reproduce

Copy paste the below grammar and execute Firm class. Try to expand the Firm class in explorer tree you keep on seeing Firm class when you expand person property.

### Model data

```text
###Relational
Database my::db
(
  Table PersonTable
  (
    NAME CHAR(200),
    FIRMID INTEGER
  )
  Table FirmTable
  (
    FIRMNAME CHAR(200),
    ID INTEGER
  )

  Join Firm_Person(PersonTable.FIRMID = FirmTable.ID)
)


###Pure
Class my::Firm
{
  legalName: String[1];
  id: Integer[1];
}

Class my::Person
{
  name: String[1];
  firmID: Integer[1];
}

Association my::Employment
{
  firm: my::Firm[*];
  employees: my::Person[*];
}


###Mapping
Mapping my::map
(
  my::Person[per1]: Relational
  {
    ~mainTable [my::db]PersonTable
    name: [my::db]PersonTable.NAME
  }
  my::Firm[fir1]: Relational
  {
    ~mainTable [my::db]FirmTable
    legalName: [my::db]FirmTable.FIRMNAME
  }

  my::Employment: Relational
  {
    AssociationMapping
    (
      firm[per1,fir1]: [my::db]@Firm_Person,
      employees[fir1,per1]: [my::db]@Firm_Person
    )
  }
)
```

### Environment

```text
Windows
```

### Contribution

- [X] I would like to work on the fix for this issue

**Comment by akphi** [comment]
@gayathrir11 why is this a bug? I'd argue we're doing the right thing here, this is similar to having association between these 2 classes. This is more like an improvement we should do on our end to avoid this kind of display. I'd argue further to only take care of association, if the user create the loop via composition like this, it would be harder to do analytics on.

**Comment by MauricioUyaguari** [comment]
It is an improvement, not a bug but we should do this. At the minimum for associations. For non-associations what kind of analytics will it make harder to do? We could just consider them `unmapped` if a loop occurs.
