### ISSUE TITLE
Support auto-complete/suggestion for filter and post filter value

### ISSUE THREAD

**Issue by MauricioUyaguari** [finos/legend-studio#1203]
### Similar requests

- [X] I have searched and found no existing similar requests

### How are you using Studio?

Legend Query

### What problems are you trying to solve?

For a better user experience allow users the ability to filter by specific values. This would entail adding search filtering on the filter and post filter tree. 

### Describe the solution you would like to see implemented

For this feature we would need to search depending on the filter value the user has types. We would  most likely need to create a query that would return a list of all possible filter values taking into account of what the user has types. 
Example filter by name and user write `$x.name = 'Jo"  would return "Jonnathan, John" as options for the user. 

### Contribution

- [ ] I would like to work on this feature

**Comment by akphi** [comment]
Duplicates of #1382
