### ISSUE TITLE
Feature request: Handle overloading functions

### ISSUE THREAD

**Issue by MauricioUyaguari** [finos/legend-studio#1211]
### Similar requests

- [X] I have searched and found no existing similar requests

### How are you using Studio?

Legend Studio

### What problems are you trying to solve?

Support overloading functions with same name but different params. 
This is already handled by [@finos/legend-engine ](https://github.com/finos/legend-engine) compilation but is not handled by studio's builder. 

### Sample Grammar to support

```
function model::test(a: String[1]): String[1]
{
  'a';
}

function model::test(a: String[1], b: Integer[1]): String[1]
{
  'a';
}
```

### Describe the solution you would like to see implemented

Differentiate between `functionName` and `name`.
For the two functions above their `functionName` would be the same `test`, but their name would be different `test_String_1_String_1_` vs `test_String_1_Integer_1_String_1_`  respectively. 

The graph building of function, transformation, and function editor would need to be updated to generate this `name` and in `PureModel` and index it so we can allow duplicates. Function Editor would be updated to update `name` and `functionName` 

### Contribution

- [ ] I would like to work on this feature

**Comment by YannanGao-gs** [comment]
Implementation plan

- [ ]  Fix Engine roundtrip process. /pure/v1/grammar/jsonToGrammar/model will add one new ### Pure among each overloaded functions e.g.
```
function model::test(a: String[1]): String[1]
{
  'a';
}
### Pure
function model::test(a: String[1], b: Integer[1]): String[1]
{
  'a';
}
```

- [ ] graph building of function
- [ ] v1-metaModel transformation
- [ ] Update Model explorer panel to display function full signature instead of functionName
- [ ] function editor

**Comment by akphi** [comment]
> Fix Engine roundtrip process. /pure/v1/grammar/jsonToGrammar/model will add one new ### Pure among each overloaded functions e.g.

Why do we want to do this?

Will think about the rest of the points in SDLC

**Comment by akphi** [comment]
Isn't it the case of engine that we will change grammar parser to correctly generate the right packageable element now?

**Comment by YannanGao-gs** [comment]
> Isn't it the case of engine that we will change grammar parser to correctly generate the right packageable element now?
Yes, update parser will fix the current behavior.

**Comment by akphi** [comment]
Why didn't we mention @kevin-m-knight-gs approach here?

**Comment by akphi** [comment]
To clarify, for `sdlc` (1) and (2) are quick hacks, (2) is stricter and less hacky than (1). (3) is a more generic approach proposed by @kevin-m-knight-gs to handle cases where we got any problems while trying to parse/get the entity (hence the idea of `Corrupted Entity`)

**Comment by YannanGao-gs** [comment]
> To clarify, for `sdlc` (1) and (2) are quick hacks, (2) is stricter and less hacky than (1). (3) is a more generic approach proposed by @kevin-m-knight-gs to handle cases where we got any problems while trying to parse/get the entity (hence the idea of `Corrupted Entity`)

Based on our earlier meeting, we will resolve this ticket using the second approach for now. 
Link this pr to [Engine PR ](https://github.com/finos/legend-engine/pull/759) and [SDLC PR ](https://github.com/finos/legend-sdlc/pull/515). 

TODO: A error handling strategy will be implemented to handle any non backward compatible changes.
