### ISSUE TITLE
Add validation for query parameters

### ISSUE THREAD

**Issue by MauricioUyaguari** [finos/legend-studio#1269]
### Similar requests

- [X] I have searched and found no existing similar requests

### How are you using Studio?

Legend Studio

### What problems are you trying to solve?

Add validation for parameter names. 
No Duplicate parameter names and no empty parameter names

### Describe the solution you would like to see implemented

Add validation for parameter names. Disable adding new parameter with same names or empty names

### Contribution

- [ ] I would like to work on this feature

**Comment by beekemarie** [comment]
@MauricioUyaguari - do we have a video walkthrough for this feature enhancement as well?
