### ISSUE TITLE
Feature request: Support preview of Markdown for text element editor

### ISSUE THREAD

**Issue by beekemarie** [finos/legend-studio#129]
### Motivation

For text element editor, if the user select the type to be `markdown`, it would be nice to have a side panel to preview the markdown text. [react-markdown](https://www.npmjs.com/package/react-markdown) seems like a good library to use in this case.

**Comment by sarthakmalik0810** [comment]
@beekemarie Hi, can I work on this issue? This is going to be my first issue. If you could point me in the right direction, it would be really helpful.

**Comment by akphi** [comment]
Closed by #1282
