### ISSUE TITLE
Feature request: Optimize 'real estate' on Query screen

### ISSUE THREAD

**Issue by YannanGao-gs** [finos/legend-studio#1300]
### Similar requests

- [X] I have searched and found no existing similar requests

### How are you using Studio?

Legend Query

### What problems are you trying to solve?

Few improvements:

- [ ] Move 'advanced' button up to not waste a line of space for only this button
- [ ] The space for setup panel could be compressed
- [x] Parameter panel should be hidden by default

### Describe the solution you would like to see implemented

Few improvements:

- [ ] Move 'advanced' button up to not waste a line of space for only this button
- [ ] The space for setup panel could be compressed
- [x] Parameter panel should be hidden by default

### Contribution

- [X] I would like to work on this feature

**Comment by akphi** [comment]
This has been partially done in https://github.com/finos/legend-studio/pull/1298, as part of https://github.com/finos/legend-studio/issues/1424 we will cleanup the flow with support for workflows, hence, be able to cleanup that area better.
