### ISSUE TITLE
Feature request: Improve user experience when they import gitlab projects in studio

### ISSUE THREAD

**Issue by gayathrir11** [finos/legend-studio#1329]
### Similar requests

- [X] I have searched and found no existing similar requests

### How are you using Studio?

Legend Studio

### What problems are you trying to solve?

Users have to import their gitlab projects inorder to start their modelling in studio. After importing their project they need to commit a review in their gitlab project to complete the import. Right now we don't have any checks to know whether user has done this step or not. Even without finishing this step users can go and create a workspace and start modelling in it. We shouldn't allow users to do that because their project is configured properly and once their project configuration is done they lose all the changes they have done before. We want to avoid users ending up in this situation.

### Describe the solution you would like to see implemented

`SDLC` finos/legend-sdlc#524
- [x]  Create an endpoint in sdlc `api/projects/{projectId}/configuration/isProjectConfigured` that makes sure that the project is succesfully imported in studio. This endpoint checks for `project.json` file in the project to decide whether the project is configured correctly or not
- [x] Add a path paramter to `​/projects​/{projectId}​/reviews` which fetches the review from a `sourceWorkspace` we mention. This is used to fetch the Project Structure review url

`Studio`
- [x] Show warning to the user when they selected a project which is not configured from the project selector dropdown
- [x] Give user an option to visit the MR for project structure so that they can merge and coonfigure their project correctly
- [x] Throw an error when user tries to create a new workspace 
- [x] Disable the option to edit workspace when the project is not configured properly

Implement the same things when user tries to update project service query and service query

### Contribution

- [X] I would like to work on this feature

**Comment by MauricioUyaguari** [comment]
@gayathrir11  @akphi  should we disable the view project option when it is misconfigured? Would be a good chance to show something if they open the view project. Maybe a warning `Not configured`.

**Comment by akphi** [comment]
> @gayathrir11 @akphi should we disable the view project option when it is misconfigured? Would be a good chance to show something if they open the view project. Maybe a warning `Not configured`.

Great point, I think we don't disable and when people view it, we can warn them about the misconfiguration
