### ISSUE TITLE
Feature request: Highlight already used properties in explorer tree of query builder

### ISSUE THREAD

**Issue by gayathrir11** [finos/legend-studio#1344]
### Similar requests

- [X] I have searched and found no existing similar requests

### How are you using Studio?

Legend Studio

### What problems are you trying to solve?

Highlight already used properties in explorer tree of query builder

### Describe the solution you would like to see implemented

- [x] Highlight already used options in explorer tree when used in `projection` panel or `graphFetch` panel
- [x] Add a config option to explorer tree whether to grey out already used properties or not
- [x]  Set the above mentioned config option as default

### Contribution

- [X] I would like to work on this feature

**Comment by gayathrir11** [comment]
@akphi  @MauricioUyaguari  do we want to grey out the property icon till the parent or just for the property alons?

**Comment by akphi** [comment]
*highlight - you mean?

I think we should highlight the parent as well since user hasn't exploded the tree in the beginning
