### ISSUE TITLE
Bug: query builder UI crashed when alternately executing queries that have columns or no columns in projection panel

### ISSUE THREAD

**Issue by YannanGao-gs** [finos/legend-studio#1356]
### Similar issues

- [X] I have searched and found no existing similar issues

### How are you using Studio?

Legend Query

### Current and expected behavior

https://user-images.githubusercontent.com/73408381/181871198-8f763fe1-76a6-4fd8-ad2d-7fbe78ca4cb3.mov

### Contribution

- [ ] I would like to work on the fix for this issue

**Comment by YannanGao-gs** [comment]
May close this one as https://github.com/finos/legend-studio/pull/1359 has been merged 
@akphi @MauricioUyaguari

**Comment by akphi** [comment]
There's that, but it doesn't address the real issue, I have fixed this in https://github.com/finos/legend-studio/pull/1388/commits/983c2f35527ce53aaebc53063725fda80720630e
