### ISSUE TITLE
Feature request: persistence trigger extensions

### ISSUE THREAD

**Issue by davidsunglee** [finos/legend-studio#1360]
### Similar requests

- [X] I have searched and found no existing similar requests

### How are you using Studio?

Legend Studio

### What problems are you trying to solve?

Allow other modules to extend persistence specifications with custom trigger definitions, e.g. for triggers specific to different persistence platforms OR for non open-sourced trigger mechanisms.

### Describe the solution you would like to see implemented

Use standard extension mechanism via PureProtocolProcessorPlugin. Only requesting text mode support at this time.

### Contribution

- [X] I would like to work on this feature

**Comment by akphi** [comment]
I will close this issue now, since I suppose this is closed by https://github.com/finos/legend-studio/pull/1361. If I'm mistaken, please feel free to re-open. Thanks!
