### ISSUE TITLE
Bug: Default date value specification editor is throwing cast compilation error

### ISSUE THREAD

**Issue by YannanGao-gs** [finos/legend-studio#1391]
### Similar issues

- [X] I have searched and found no existing similar issues

### How are you using Studio?

Legend Query

### Current and expected behavior

<img width="628" alt="Screen Shot 2022-08-09 at 4 15 59 PM" src="https://user-images.githubusercontent.com/73408381/183752767-8c67de03-56d3-4c87-9777-03756f06c008.png">

### Contribution

- [X] I would like to work on the fix for this issue

**Comment by akphi** [comment]
Reopened, see the issue in https://github.com/finos/legend-studio/issues/1460 when drag-and-drop a derived property with a parameter of type `Date`, we automatically populate a dummy value of type `StrictDate`, causing a compilation error
