### ISSUE TITLE
Feature request: Use External Formats Apis for Model Imported 

### ISSUE THREAD

**Issue by MauricioUyaguari** [finos/legend-studio#1438]
### Similar requests

- [X] I have searched and found no existing similar requests

### What problems are you trying to solve?

Related to https://github.com/finos/legend-engine/issues/703
External Formats will be the strategy moving forward in how to seralize/deseralize schemas to and from models. 
We will remove the usage of model loading through the import schema generator api. 
Moving forward we will get the supported schemas that generate models to show in the Model Importer 

### Describe the solution you would like to see implemented

Replace previous apis and use external format apis

- introduces an improved UI for loading files (multi file input) 
- configs for model generation
- ability to generate binding/schemaset in addition to the models from a schema

### Contribution

- [X] I would like to work on this feature

**Comment by akphi** [comment]
Closed by #1432
