### ISSUE TITLE
Bug: Opening Query with uncompiled graph causes Invalid UI State

### ISSUE THREAD

**Issue by MauricioUyaguari** [finos/legend-studio#1460]
### Similar issues

- [X] I have searched and found no existing similar issues

### How are you using Studio?

Legend Studio

### Current and expected behavior

When opening a query with an uncompiled graph, text mode is opened but the query builder modal is also opened on top. This causes an invalid state as the query being editable is no longer part of the graph. It also does not let you close the query builder modal causing users to lose their local changes. 

### Steps to reproduce

Open the query builder for the service, try to drag and drop in `prop2`, a derived property
Hit Save Query
Try to close the query builder
We should see the query builder becomes blank

https://user-images.githubusercontent.com/13574879/188937269-11d8cd56-d7b1-49f7-ae11-532c02533b5c.mov

### Model data

```
###Service
Service model::MyService
{
  pattern: '/45f40337-e6d2-45fe-93c1-82ef3eccb2ea';
  documentation: '';
  autoActivateUpdates: true;
  execution: Single
  {
    query: |model::A.all()->project([x|$x.prop1], ['Prop1']);
    mapping: model::MyMapping;
    runtime: model::MyRuntime;
  }
}


###Pure
Class model::A
{
  prop1: String[1];
  prop2(param: Date[1]) {''}: String[1];
}


###Mapping
Mapping model::MyMapping
(
  *model::A: Pure
  {
    ~src model::A
    prop1: $src.prop1
  }
)


###Runtime
Runtime model::MyRuntime
{
  mappings:
  [
    model::MyMapping
  ];
  connections:
  [
    ModelStore:
    [
      connection_1:
      #{
        JsonModelConnection
        {
          class: model::A;
          url: 'data:application/json,%7B%7D';
        }
      }#
    ]
  ];
}

```

### Contribution

- [ ] I would like to work on the fix for this issue

**Comment by akphi** [comment]
Updated the description
