### ISSUE TITLE
Bug: Duplicated property mapping for property type other than class should be handled properly

### ISSUE THREAD

**Issue by akphi** [finos/legend-studio#1461]
### Similar issues

- [X] I have searched and found no existing similar issues

### How are you using Studio?

Legend Studio

### Current and expected behavior

When we mapped a property mapping twice in a class mapping and that property is primitive/measure/unit/enumeration (i.e. non-class) we should throw an error or warn about this instead of crashing the app like right now.

> Note that this applies to `enumeration mapping` as well. 

_Originally raised in https://github.com/finos/legend/issues/531 - whether we fail this compilation in `engine` or not is not something we will care about, we need to have some handling around this case in mapping editor_

> We can employ the same strategy we used before for warning about duplicated properties in class-editor. `Engine` could throw warnings about this, In `Studio`, we probably should prune the latter one, i.e the first property mapping specified wins.

### Steps to reproduce

Use the provided Pure code.
Open the mapping `model::MyMapping` in form mode
Open class mapping for `model::Person`
We should see the app crash

### Model data

```text
Class model::Person
{
  name: String[1];
}


###Mapping
Mapping model::MyMapping
(
  *model::Person: Pure
  {
    ~src model::Person
    name: $src.name,
    name: $src.name
  }
)
```

### Contribution

- [ ] I would like to work on the fix for this issue

**Comment by YannanGao-gs** [comment]
Implementation Plan

- [ ] Highlight the name of duplicated property mappings
- [ ] When hovering over the 'x' icon, display error message
- [ ] Enable a 'x' button to delete the corresponding property mapping
<img width="609" alt="Screen Shot 2022-09-22 at 4 56 49 PM" src="https://user-images.githubusercontent.com/73408381/191849542-ba7e3c3e-b3d4-422b-bd24-81b269a71cd0.png">
