### ISSUE TITLE
Feature request: Make project groupId in project creation form configurable 

### ISSUE THREAD

**Issue by epsstan** [finos/legend-studio#1499]
### Similar requests

- [X] I have searched and found no existing similar requests

### How are you using Studio?

Legend Studio, Docker images (e.g. finos/legend-studio)

### What problems are you trying to solve?

The "groupId" field in the project creation form has a hardcoded default value.

```
See  ./packages/legend-application-studio/src/components/workspace-setup/ProjectCreateModal.tsx
          <input
            className="panel__content__form__section__input"
            spellCheck={false}
            placeholder="org.finos.legend.*"
            value={groupId}
            onChange={changeGroupId}
          />
```
While "org.finos.legend" is a reasonable default for FINOS-hosted projects, it is not a reasonable default for projects not hosted by FINOS.  

### Describe the solution you would like to see implemented

Can the default groupId value be sourced from the Studio server/app configuration instead of being hardcoded in code ?

### Documentation, Design, Adoption, Migration Strategy

If the groupId can be sourced from the configuration, we can ship a configuration with a default value such as "com.demo.legend". Also, the configuration files that ship with the Docker container can be parameterized to allow users to inject this when running the Studio container.

### Contribution

- [ ] I would like to work on this feature

**Comment by akphi** [comment]
Thanks! This makes sense, we'll take care of it. 

Also, re-formatted the description.
