### ISSUE TITLE
Feature request: Support `olapGroupBy` in Query Builder

### ISSUE THREAD

**Issue by MauricioUyaguari** [finos/legend-studio#1527]
### Similar requests

- [X] I have searched and found no existing similar requests

### What problems are you trying to solve?

Support the `olapGroupBy` function in pure.
 The `olapGroupBy` function is a function applied to a `TDS` (after `project`) function that applies window functions to the TDS. 

Window functions enable users to perform calculations against partitions (i.e. subgroups or sections) of a result set, typically a table or the results from another query. Unlike traditional aggregation functions, which return only a single value for each group defined in the query, window functions return a single value for each input row.

https://chartio.com/resources/tutorials/using-window-functions/

### Describe the solution you would like to see implemented

the function we aim to support is defined as 
`meta::pure::tds::olapGroupBy<T>(tds:TabularDataSet[1], columns:String[*], sortBy:SortInformation[0..1],operation:FunctionDefinition<{TDSRow[*]->Map<Any,Integer>[1]}>[1],columnName:String[1])`

Things to Consider/Disuss 
- [x] ensure we offer sortBy as optional
- [x] enforce order of `olapGroupBy`. should it be between fetch structure and post filter?
- [ ] `operation` how loose should it be. provide a list of 
- [ ] list of columns can be empty see: `meta::relational::tests::tds::tdsWindow::testOLAPGroupBySnowflake`

Takes in a TDS, columns, a sort function, and a tds function (operator). 

Ensure we support/test the following. See following [pure tests](https://github.com/finos/legend-engine/blob/master/legend-engine-xt-relationalStore-pure/src/main/resources/core_relational/relational/tds/tests/testTDSWindowColumn.pure)

- [ ] percentile functions
    - `         Person.all()
            ->project([col(p|$p.firstName, 'firstName'), col(p|$p.lastName, 'lastName'), col(p|$p.age, 'age')])
            ->olapGroupBy(['firstName'], func('age', y | $y->percentile(0.9)), 'testCol1')`
- [ ] Using the `meta::pure::tds::func(f: FunctionDefinition<{TDSRow[*]->Map<Any,Integer>[1]}>[1]): TdsOlapRank<TDSRow>[1]`
    - `->project([col(p|$p.firstName, 'firstName'), col(p|$p.lastName, 'lastName'), col(p|$p.age, 'age')])
                            ->olapGroupBy(['firstName'],desc('lastName'), func(y|$y->rank()),'testCol1')`
- [ ] sort information takes column and sort order such as `^SortInformation(column=$column, direction=SortDirection.DESC)`. ensure these are registered in [legend-engine](github.com/finos/legend-engine).

Known olap specific functions (https://github.com/finos/legend-engine/blob/master/legend-engine-pure-code-compiled-core/src/main/resources/core/pure/corefunctions/mathExtension.pure)
- `meta::pure::functions::math::olap::rank`
- `meta::pure::functions::math::olap::denseRank`
- `meta::pure::functions::math::olap::averageRank`
- `meta::pure::functions::math::olap::rowNumber`

**Comment by akphi** [comment]
Closed by https://github.com/finos/legend-studio/pull/1530
