### ISSUE TITLE
Bug: Fail to delete old folders after updating element's path via rename 

### ISSUE THREAD

**Issue by YannanGao-gs** [finos/legend-studio#1556]
### Similar issues

- [X] I have searched and found no existing similar issues

### How are you using Studio?

Legend Studio

### Current and expected behavior

Fail to delete old folders after updating element's path via rename 

https://user-images.githubusercontent.com/73408381/195431436-d3ff3123-16b4-4193-ad35-fc44586c383e.mov

### Contribution

- [ ] I would like to work on the fix for this issue

**Comment by akphi** [comment]
This is actually intended behavior, you just rename the file here, the package should stay. Also, think about it, if people create an empty package you would get the same thing, so we can't really say this is bad state neither.
