### ISSUE TITLE
Feature request: Improve editing of multiplicity for parameters in query builder

### ISSUE THREAD

**Issue by YannanGao-gs** [finos/legend-studio#1617]
### Similar requests

- [X] I have searched and found no existing similar requests

### How are you using Studio?

Legend Query

### What problems are you trying to solve?

Want to guide users into creating valid queries when adding parameters. Right now only required, optional and list parameters
are supported. Additionally the editing of multiplicity was not user friendlty as its hard for users to understand lower and upper bound of multiplicity. 

### Describe the solution you would like to see implemented

Add the following options for parameters
- required
- optional
- list 

else highlight in red so users know their multiplicity

**Comment by akphi** [comment]
We should also take into account the parameter editor that we pops up when we `run query`, the default generated value should take into account multiplicity

https://github.com/finos/legend-studio/blob/12a63454e29f8bd9ce22c1f4fe37e1a9a28fb2a7/packages/legend-query-builder/src/stores/shared/ValueSpecificationEditorHelper.ts#L95-L135
