### ISSUE TITLE
Bug: Discrepancy in DND TDS to Filter Panel   

### ISSUE THREAD

**Issue by xannem** [finos/legend-studio#1707]
### Similar requests

- [X] I have searched and found no existing similar requests

### How are you using Studio?

Legend Query

### What problems are you trying to solve?

dragging proejction panel column into filter :) no equivalent behavior bc projection panel we drag into filter but do not work with group filter 

Currently, dragging a property from the explorer panel to the filter panel will allow users to group nodes together. However, this same type of behavior is not possible when you drag nodes from the fetch structure panel to the filter panel. 

![Kapture 2022-11-17 at 14 53 51](https://user-images.githubusercontent.com/41248956/202546188-1f483262-8f00-4cd2-b400-ab98019e90cc.gif)

### Describe the solution you would like to see implemented

Consider supporting or having a good reason not to have same behavior. 

### Contribution

- [ ] I would like to work on this feature

**Comment by akphi** [comment]
@MauricioUyaguari what do you think about this? Should we count this as a bug. Honestly, the feature seems fine to me: i.e. the only filter one can create out of a projection panel is a simple top level condition 🤷
