### ISSUE TITLE
Feature request: Show all options in Query home screen

### ISSUE THREAD

**Issue by epsstan** [finos/legend-studio#1902]
### Similar requests

- [X] I have searched and found no existing similar requests

### How are you using Legend?

Legend Query

### What problems are you trying to solve?

The home page of Query does not show all the available options. 

![query-front](https://user-images.githubusercontent.com/5117593/218293450-0ceeb356-847b-42bf-bc0c-aa1bc8de9e8d.png)

The little "..." and the "V" are not obvious.

### Describe the solution you would like to see implemented

Showing all the options, I think, will make it easy for users.

### Contribution

- [ ] I would like to work on this feature

**Comment by epsstan** [comment]
Here's an example https://gitlab.com/-/graphql-explorer

**Comment by akphi** [comment]
> Here's an example https://gitlab.com/-/graphql-explorer

@epsstan I think you meant https://github.com/finos/legend-studio/issues/1901

As for this issue, we have made a lot of considerations about what should and should not be shown by default and condensed to just those options. However, you can tailor this view: The `cog gear` icon for `settings` would allow you to show more options (more categories and advanced options within each), by choosing them, the URL would be updated and if one prefers a particular view, one can send around and bookmark that URL instead. We can potentially have `presets` of URL for example, `/query/sdlc` for `sdlc` category 🤔. Anyhow, I don't think we would change this screen anytime soon, so I'll be closing this for now.

**Comment by epsstan** [comment]
K. I guess my point is that it is currently not obvious how to navigate. The last time I used  Query,  creating a Query from a mapping was available on the home screen. And it took me some time to figure out this option was now tucked away. 

I'm sure you have thought about the UX here. My ten cents - If there's enough screen space, why not show all the options, especially it till reduce the # of clicks. 

Is there a preset to "show all" ? This can be useful for users trying Legend for the first time,

**Comment by MauricioUyaguari** [comment]
The thought behind this, is that those options are more for advanced users. Presenting all of the options to every user will confuse users even more as they won't know where to start. 

The url `/setup?showAdvancedActions=true&showAllGroups=true` will show setup with all options showing.

**Comment by akphi** [comment]
> Is there a preset to "show all" ? This can be useful for users trying Legend for the first time,

I guess we could add that 🤔 but probably under `setting`, like said, we first started out with showing all options then realize it was more than needed by the majority of the users and actually confused them to a certain degree (sadly), so we simplified

 


> K. I guess my point is that it is currently not obvious how to navigate. The last time I used Query, creating a Query from a mapping was available on the home screen. And it took me some time to figure out this option was now tucked away

Indeed, you're definitely one of the users with advanced use cases 😄
