### ISSUE TITLE
Bug: Fix dispatch logic for key bindings so that it executes for the correct command key

### ISSUE THREAD

**Issue by gayathrir11** [finos/legend-studio#1969]
### Similar issues

- [X] I have searched and found no existing similar issues

### How are you using Studio?

Legend Studio

### Current and expected behavior

Currently we support multiple commands in studio for the same key combinations. We have a dispatch logic for the command getting executed when a particular key combination is pressed in application. This logic makes sure that we only run the command once even if we have multiple commands with the same combination. But it doesn't encounter the fact the `KeyBindingConfig` has entries for multiple commands with the same key combination. In this scenario the dispatch function itself gets called twice. 
Inorder to make sure that we run the command once we need to have some logic in dispatch function that checks not just the key combination but the command key too.

### Steps to reproduce

Press `F9` in studio or embedded query. You notice that compile function gets called twice

### Contribution

- [X] I would like to work on the fix for this issue

**Comment by akphi** [comment]
The approach taken in #1970 is very sensible, but unfortunately, we include the command logic in `KeyBinding` which is lower level utility layer, as such, I took a more simplistic approach in #1973
