### ISSUE TITLE
Bug: Inconsistent light theme support for execution plan viewer

### ISSUE THREAD

**Issue by gayathrir11** [finos/legend-studio#1998]
### Similar requests

- [X] I have searched and found no existing similar requests

### How are you using Legend?

Legend Query

### What problems are you trying to solve?

If we open execution plan viewer in light theme of query we notice that the light theme is not applied consistently when we have relational nodes to show in the plan
![plan](https://user-images.githubusercontent.com/87973126/224712531-8089d877-46bb-47e7-a1c7-2e5c9e1710e9.PNG)

### Describe the solution you would like to see implemented

We should apply light theme consistently so that if an execution plan has relational nodes it should be able to show in light theme

### Contribution

- [ ] I would like to work on this feature

**Comment by akphi** [comment]
I would actually put this as a bug

**Comment by gayathrir11** [comment]
Issue can be closed as the light theme support is consistent now. Addressed in this PR: https://github.com/finos/legend-studio/pull/2124/files
