### ISSUE TITLE
Bug: Typo in "Model Conneciton" in "Create a new connection" screen

### ISSUE THREAD

**Issue by epsstan** [finos/legend-studio#240]
## 🐛 Bug Report

The drop down list in the "Create a new connection" screen has the option "Model Connection" instead of "Model Connection"

### Additional context

Also see typos in NewElementState.tsx. Search for CONNECITON

**Comment by akphi** [comment]
@epsstan hah! Thanks for reporting and tracing the root cause of the bug 🙏
