### ISSUE TITLE
Feature request: Execution Plan Viewer MVP

### ISSUE THREAD

**Issue by nayanika2** [finos/legend-studio#289]
### Motivation
The execution plan holds all the information required for the engine server (legend-engine) to execute a query. With this viewer, we plan to shed some light on the context of the execution plan and showcase to the user the steps taken to execute their queries to provide the data in the shape they want it.

Since the execution plan holds various types of nodes for different types of queries and data sources, it is not feasible to inaugurate a user interface covering all use cases. For this reason, this feature will be implemented in steps. We will cover basic relational, model-to-model cases in the beginning and lead up to more advanced use cases. For the nodes not supported we will default to a basic JSON string viewer.

### Implementation

- [x] Create a Wireframe for Interface.
- [x] Create UI for explorer tree.
- [x] Create UI for SQLExecution Node.
- -  [x] Query
-  - [x] Result Colums
- - [x] Connection
- [x] Create UI for Root execution Node.
- [ ] Create UI for Serializer,Template functions.
- [x] Able to switch between JSON view and form view.

### Wireframe for UI

![query](https://user-images.githubusercontent.com/86055213/123394995-57974a00-d5bd-11eb-8665-ffb6ad52210b.png)

![result](https://user-images.githubusercontent.com/86055213/123395013-5bc36780-d5bd-11eb-8d4a-005b1c899748.png)

**Comment by akphi** [comment]
@nayanika2 Looking great! I would say we add one more item right after the wireframe for creating the explorer. Also for the explorer, `execution plan` should be the only node, when clicking on it, you would then be able to view the `template functions` and `serializer` on the right side. What do you think?

**Comment by nayanika2** [comment]
> @nayanika2 Looking great! I would say we add one more item right after the wireframe for creating the explorer. Also for the explorer, `execution plan` should be the only node, when clicking on it, you would then be able to view the `template functions` and `serializer` on the right side. What do you think?

I have added the explorer as the 5th task ,And yeah about the second point I will update it according to your suggestion.Thanks!!

**Comment by akphi** [comment]
Closing as this is done in #368
