### ISSUE TITLE
Bug: Mapping builder fails to consider include mappings when resolving class mappings

### ISSUE THREAD

**Issue by MauricioUyaguari** [finos/legend-studio#292]
## 🐛 Bug Report

When resolving class mappings during the building the metamodel mapping, the builder fails to look in the include mappings for the target class mappings. 

### Step to Reproduce

Copy test grammar below into text mode. The grammar will compile with legend engine but will fail against studio's building of the metamodel. This is due to the builder not resolving the class mapping `model_Person` in the included mappings. We should look to ensure the mapping editor handles this gracefully as we don't search in the included mappings for class mappings. 

```
Class model::SPerson
{
  firstName: String[1];
  lastName: String[1];
}

Class model::Person
{
  fullName: String[1];
}

Class model::Firm
{
  name: String[1];
  employees: model::Person[1];
}

Class model::SFirm
{
  employees: model::SPerson[1];
  name: String[1];
}


###Mapping
Mapping model::IncludeMapping
(
  *model::Person: Pure
  {
    ~src model::SPerson
    fullName: $src.firstName + ' ' + $src.lastName
  }
)

Mapping model::M2MMapping
(
  include model::IncludeMapping

  *model::Firm: Pure
  {
    ~src model::SFirm
    name: $src.name,
    employees[model_Person]: $src.employees
  }
)
```

### Expected behavior
When building a mapping and resolving a class mapping, the builder should also look at the include mappings.

**Comment by akphi** [comment]
@MauricioUyaguari I think this is related to the bug where `query builder` not detecting certain properties as `mapped`, so let's prioritize this.
