### ISSUE TITLE
Bug: Query builder: Allow execute/build-query on entities from dependencies/generated elements

### ISSUE THREAD

**Issue by akphi** [finos/legend-studio#302]
## 🐛 Bug Report

Right-clicking to execute (i.e. opening query builder) right now is not supported for elements from dependencies and generated elements

**Comment by MauricioUyaguari** [comment]
Reopening as the original MR enables query builder but doesn't total enable query builder as we don't fetch mappings/runtimes in the dependency/generation models.

**Comment by akphi** [comment]
@MauricioUyaguari is this fixed now?

**Comment by MauricioUyaguari** [comment]
Yes @akphi  closed by https://github.com/finos/legend-studio/pull/588
