### ISSUE TITLE
Bug: Studio reads in values in scientific notation and leaves them as is (using lossless-json library)

### ISSUE THREAD

**Issue by aziemchawdhary-gs** [finos/legend-studio#321]
## 🐛 Bug Report

For values sent by the engine, Studio is keeping values in scientific notation rather than keeping/converting to decimals. Previously, when we still use `JSON.parse`, values like `1.0E-4` is converted to `0.0001` but with the [lossless-json](https://github.com/josdejong/lossless-json) (which we use in replacement of `JSON.parse` to make sure values like `1.000` is not converted to `1`), these values are kept in scientific notation format.

### Step to Reproduce

Example code given below. When executing tests with the example, using values such as `0.0001` are shown in Studio as `1.0E-4`. 

### Expected behavior

With values such as `0.0001`, the expected result/test result should keep the value as `0.0001`. 
This works for values such as `0.0001`, `0.001`, `0.1`, etc.

### Reproduction Code or Repo

Example to reproduce:

```
Class test::A
{
  f: Float[1];
}


###Mapping
Mapping test::AtoA
(
  *test::A: Pure
  {
    ~src test::A
    f: $src.f
  }

  MappingTests
  [
    test_1
    (
      query: |test::A.all()->graphFetchChecked(#{test::A{f}}#)->serialize(#{test::A{f}}#);
      data:
      [
        <Object, JSON, test::A, '{"f":0.0001}'>
      ];
      assert: '{}';
    )
  ]
)
```

### Possible Solution

I think lossless-json library is causing the issue here, and likely we need to do some work to change back to the decimal format that is expected by users.

**Comment by akphi** [comment]
@aziemchawdhary-gs Thank you so much! I did some small formatting edits for the description

**Comment by aziemchawdhary-gs** [comment]
Actually on further thought/investigation, I think Studio and lossless-json is working correctly as you mention. 

From the users POV, this behaviour is strange - they put in 0.0001 as the input, define an identity mapping but the result in Studio is printed as 1.0E-4. They are the same number but different formatting.

However - this is actually a Java serialization issue I think. Printing out a float such as 0.0001f in Java produces 1.0E-4

Happy to close this issue - I think this is a problem that needs to be solved (if possible) on the M2M Java code generation side.
