### ISSUE TITLE
Bug: Diagram is not getting updated when the graph changes

### ISSUE THREAD

**Issue by akphi** [finos/legend-studio#335]
## 🐛 Bug Report

Reported by @beekemarie

When adding or removing relationships between classes, the diagram does not reflect the changes and I need to remove the class and drag it back into the diagram

### Step to Reproduce
1. Create 2 classes
2. Create a diagram and drag & drop the classes in the diagram
3. Map/Link classes
4. Go back to the diagram: relationship between classes not displayed

### Expected behavior
1. Create 2 classes
2. Create a diagram and drag & drop the classes in the diagram
3. Map/Link classes
4. Go back to the diagram. Relationship displayed.

**Comment by pierredebelen** [comment]
Should be fixed by https://github.com/finos/legend-studio/pull/351
