### ISSUE TITLE
Feature request: Ability to easily share complete stack trace of errors/exceptions

### ISSUE THREAD

**Issue by vikask-gs** [finos/legend-studio#337]
## 🚀 Feature Request

Can we create something in studio UX to easily obtain complete trace of errors/exceptions? When users share one line errors with developers, there is not enough information in them to understand, what’s going on.

**Comment by akphi** [comment]
Thank you for your feedback. This is already mentioned in https://github.com/finos/legend-studio/issues/291 https://github.com/finos/legend-studio/issues/273. We will redesign our notification to show the full error message and we will print them out to the console as well.
