### ISSUE TITLE
Bug: Configuration editor breaks application while in Viewer Mode

### ISSUE THREAD

**Issue by MauricioUyaguari** [finos/legend-studio#354]
## 🐛 Bug Report

Config editor, used to edit the project's configuration, breaks while in viewer mode. 

### Step to Reproduce

Make sure that the project being used have a non-zero project structure version
Open a project in viewer mode and open the config editor. The application will crash.

**Comment by akphi** [comment]
Closing as this is already a listed task of https://github.com/finos/legend-studio/issues/297
