### ISSUE TITLE
Bug: `PromoteToService` fails when going from a relational mapping execution

### ISSUE THREAD

**Issue by MauricioUyaguari** [finos/legend-studio#375]
## 🐛 Bug Report

When executing a relational mapping, you should be able to promote the query as a service. In doing so now, the creation of the service fails. 

### Step to Reproduce
- Create a relational mapping
- Execute the mapping using the execute feature
- `PromoteToService`
  - Expected Error -> `Unsupported Operation Error: Can't build service from input data state`

### Expected behavior
- When promoting we may need to allow users to select the relevant runtime.

**Comment by akphi** [comment]
I think Ill close this. Is it really a bug though when we clearly said we havent supported it yet?
