### ISSUE TITLE
Bug: Query builder roundtrip fails when we have a derived property in graph-fetch

### ISSUE THREAD

**Issue by akphi** [finos/legend-studio#428]
## 🐛 Bug Report

We allow users to add derived properties to the graph-fetch but the next time they work with the query, we show the property is not found.

### Step to Reproduce

```
Enum model::target::IncType
{
  LLC,
  CORP
}

Class model::target::NPerson
{
  fullName: String[1];
  age: Integer[0..1];
}

Class model::LegalEntity
{
}

Class model::Person
{
  firstName: String[1];
  lastName: String[1];
}

Class model::target::NFirm
[
  namePrefix: $this.name->startsWith('MC')
]
{
  nEmployees: model::target::NPerson[1..*];
  name: String[1];
  incType: model::target::IncType[1];
  firstEmployee() {$this.nEmployees->first()}: model::target::NPerson[0..1];
  myName(suffix: String[1],prefix: String[1]) {$prefix + $this.name + $suffix}: String[1];
}

Class model::Firm extends model::LegalEntity
[
  constraintSize: $this.employees->size() > 2
]
{
  employees: model::Person[1..*];
  legalName: String[1];
  incType: String[1];
  firstEmployee() {$this.employees->first()}: model::Person[0..1];
}


###Mapping
Mapping model::MyMapping
(
  *model::target::NPerson: Pure
  {
    ~src model::Person
    fullName: $src.firstName + ', ' + $src.lastName
  }
  *model::target::NFirm: Pure
  {
    ~src model::Firm
    nEmployees[model_target_NPerson]: $src.employees,
    name: $src.legalName,
    incType: EnumerationMapping model_target_IncType: $src.incType
  }

  model::target::IncType: EnumerationMapping
  {
    LLC: ['llc'],
    CORP: ['Corporation']
  }

  MappingTests
  [
    test_1
    (
      query: |model::target::NFirm.all()->graphFetch(#{model::target::NFirm{firstEmployee{age}}}#)->serialize(#{model::target::NFirm{firstEmployee{age}}}#);
      data:
      [
        <Object, JSON, model::Firm, '{"employees":[{"firstName":"firstName 90","lastName":"lastName 49"}],"legalName":"legalName 34","incType":"llc"}'>
      ];
      assert: '{"defects":[{"id":"namePrefix","externalId":null,"message":"Constraint :[namePrefix] violated in the Class NFirm","enforcementLevel":"Error","ruleType":"ClassConstraint","ruleDefinerPath":"model::target::NFirm","path":[]}],"source":{"defects":[{"id":"constraintSize","externalId":null,"message":"Constraint :[constraintSize] violated in the Class Firm","enforcementLevel":"Error","ruleType":"ClassConstraint","ruleDefinerPath":"model::Firm","path":[]}],"source":{"number":1,"record":"{\"employees\":[{\"firstName\":\"firstName 90\",\"lastName\":\"lastName 49\"}],\"legalName\":\"legalName 34\",\"incType\":\"llc\"}"},"value":{"incType":"llc","legalName":"legalName 34","employees":[{}]}},"value":{"incType":"LLC","name":"legalName 34"}}';
    )
  ]
)

```

Open the query of `test1` in the mapping, observe how it says it cannot find the property `firstEmployee`

### Possible Solution

We should check the logic we use to resolve properties, we might have missed out on scanning the derived property when building the property expression chain for graph fetch.

**Comment by gayathrir11** [comment]
@akphi, @MauricioUyaguari I have looked into the issue. I have noticed that `isCompatibleDerivedProperty` check is failing for the example we have here. It seems engine is returning an empty array for `derivedProperty` `parameters` and we are making a check to see that length of `propertyGraphFetchTree.parameters` matches with the length of `parameters` of  `derivedProperty`. I noticed that `propertyGraphFetchTree.parameters` has just the name of `ownerClass` of `derivedProperty`. I am not sure why we need that check. If we need it only to make sure that `ownerClass` of `derivedProperty` matches with the class we are querying from I think we can leverage this check instead of the one we have in `isCompatibleDerivedProperty`.
What do you guys think?

**Comment by MauricioUyaguari** [comment]
Created https://github.com/finos/legend-studio/issues/689 for derived properties with parameter values.

**Comment by MauricioUyaguari** [comment]
For this fix, let's make sure we add `QueryBuilder_BuildLambdaRoundtrip` test and a `QueryBuilder_LambdaProcessingRoundtrip.test` test.
