### ISSUE TITLE
RFC: Support parameters for queries

### ISSUE THREAD

**Issue by MauricioUyaguari** [finos/legend-studio#466]
## 💬 Request for Comments

Add support for parameters for queries. Incorporate parameters with supported elements like services

### Motivation
Queries often take parameters to make them more dynamic and powerful. For this feature, we aim to be able to read, edit and add parameters within a query. In addition, users should be able to provide parameter values when executing the query.

### V0 - Query Builder Parameter Basic Support
  - [x] Read parameters defined in query and display
  - [x] Allow specifying parameters of a query
  - [x] Allow editing of parameters
  - [x] Add drag and drop to filter panel
  - [x] Add drag and drop to derived properties' expressions
  - [x] Allow using parameters/variables as the RHS of filter and derived properties' expressions
  - [x] Roundtrip test using query
  - [x] `Enumeration` Support
  - [x] ValueSpec Editor

### V1 - Query Builder Parameter Execution Support
  - [x]  Disallow parameters for mapping execution, mapping test, and executing class from explorer context menu
  - [x]  When we execute the query, we send the endpoint a lambda with parameters removed and replaced by local variables

 - [ ] `BUG` executing with Enum param value set
 - [ ] rearrange panel with `direction`

### V2 - Service Editor Parameter Execution Support
  - [x] Allow specifying parameters for execution
  - [ ] Allow specifying parameters values when running test (form editor), we probably should do some type-checking
  - [ ] `BACKEND` Add grammar support for service tests with parameters
  - [ ] Add a separate panel for adding variables (primitive type only for now)

**Comment by akphi** [comment]
Edit to make it follow RFC format 😄

**Comment by MauricioUyaguari** [comment]
Closing and Moving further improvements to https://github.com/finos/legend-studio/issues/540

**Comment by akphi** [comment]
**NOTE**: Updated this to `Feature Request` instead of `RFC`
