### ISSUE TITLE
Bug: Viewer mode for single entity not working

### ISSUE THREAD

**Issue by umarphaarook** [finos/legend-studio#503]
## 🐛 Bug Report

Viewer mode for single entity not working

### Step to Reproduce

- Create a project
- Create a workspace
- Open the workspace just created
- Switch to `Text Mode`
- Copy & Paste the sample grammar in the `Reproduction Code or Repo` section below
- Compile and Sync the changes
- Create a review, Commit the review and Leave when prompted
- Select the project created in step 1
- Open the project in viewer mode by clicking the button labelled: `View Project`
- Append an entity-path `/entity/model::Person` or `/entity/model::Firm` to the project's URL in the URL bar
- Press Return/Enter

### Expected behavior

The project should automatically open the appended entity and the entity-path should be stripped out from the URL

### Reproduction Code or Repo

```
Enum model::incType
{
  LLC,
  LTD
}

Class model::Person
{
  firstName: String[1];
}

Class model::Firm
{
  incType: model::incType[1];
}
```

### Possible Solution

Avoid triggering a page reload while stripping elementPath from the URL.

### Additional context

Changing the navigator's location results in a page reload which in turn clears the `ViewerStore's elementPath` piece of state  stripped from the URL, hence no element to open.

**Comment by akphi** [comment]
@umarphaarook you can probably remove the environment info section there, also for the link you compose, I think it's better if we provide the actual steps that makes this happen, i.e. giving a grammar for workspace, and in the steps to reproduce, add the step where you merge the changes

**Comment by umarphaarook** [comment]
@akphi @MauricioUyaguari  I updated the bug issue. Currently writing a test for the fix.
