### ISSUE TITLE
Feature request: Stand alone query: Provide Mechanism to save query you dont own

### ISSUE THREAD

**Issue by MauricioUyaguari** [finos/legend-studio#531]
## 💬 Request for Comments

In stand alone query when you open a query you don't own, there is no option to copy over or save your changes as your own query. 

### Implementation Plan
- Provide a clone/save as button for queries you don't own. You would then copy over the current query and its context with the current user as the owner.

**Comment by akphi** [comment]
This has been implemented, the `create query` button is definitely there. I think if you don't see the save/create a new button pair in a query that you own, that's probably a bug with how we compute ownership of query, so closing this issue for now.

https://user-images.githubusercontent.com/13574879/140612254-d210409f-9fa6-4a0e-9185-638a81df43f4.mov
