### ISSUE TITLE
Feature request: Query parameters support improvements (phase 2)

### ISSUE THREAD

**Issue by MauricioUyaguari** [finos/legend-studio#540]
Further improvements for parameters in both `Query` and `Studio`. We have allowed specifying parameters for service execution function in query builder via https://github.com/finos/legend-studio/issues/466. Here, we want to completely close that piece as well as to allow a way to set/link parameters specified in the service URL pattern to those parameters specified for the query.

## Studio Improvements
- [ ] `MAYBE` Support service parameters coming from the URL patterns (moved from https://github.com/finos/legend-studio/issues/448)
- [ ] Allow specifying parameters values when running service test (in `ServiceEditor`), we probably should do some type-checking

## Query Improvements
- [ ] `BACKEND` improve executing with let statements `ENUM` and `COLLECTION`

## Relevant works currently being worked on
- [ ]  `BACKEND` Add grammar support for service tests with parameters

**Comment by akphi** [comment]
Closing in favor of https://github.com/finos/legend-studio/issues/942
