### ISSUE TITLE
Feature request: Allow rename mapping test

### ISSUE THREAD

**Issue by MauricioUyaguari** [finos/legend-studio#593]
**UPDATE by @akphi**

We should allow to rename mapping test from context menu

**Comment by akphi** [comment]
@MauricioUyaguari I updated the issue. I think we should stop filing `mega-thread` unless absolutely have to because I `mega-thread` issue often span across multiple milestones and it's very very hard to close them

**Comment by akphi** [comment]
Closing in favor of the refactor of testing. See #1077
