### ISSUE TITLE
Feature request: Add support for querying a versioned class (i.e. `milestoned`)

### ISSUE THREAD

**Issue by MauricioUyaguari** [finos/legend-studio#619]
### Overview
Add form support for querying against a milestone class. 
A milestone class can be defined as a class that has a stereotype (directly or through its `generalizations`) in the profile 
`meta::pure::profiles::temporal`. 
Milestone class require a `Date` input to query. Currently Query Builder does not support editing a milestone class throwing us in unsupported mode when reading and creating a miconfigured query against a milestone class. 

### Implementation
- [ ] Add profile `meta::pure::profiles::temporal` to system
- [ ] Add lambda processing/building support for milestoned classes
- [ ] Properly handle changing from milestone to non-milestone class and vice versa
- [ ] Default to `%latest` date when changing to new milestoned class
- [ ] Add editor to edit milestone date value

### Model Example
```
TODO
```

**Comment by akphi** [comment]
@gayathrir11 @MauricioUyaguari Please fill in more details when we have a better understanding of the specs. Thanks!

**Comment by akphi** [comment]
@gayathrir11 @MauricioUyaguari could we fill in the detail here now?

**Comment by gayathrir11** [comment]
**Grammar for testing:**
```
###Service
Service my::service
{
  pattern: '/e70d2c08-4169-44f1-89d4-0fa9971c3995';
  documentation: '';
  autoActivateUpdates: true;
  execution: Single
  {
    query: businessDate: Date[1]|my::Person.all($businessDate);
    mapping: my::map;
    runtime:
    #{
      mappings:
      [
        my::map
      ];
    }#;
  }
  test: Single
  {
    data: '';
    asserts:
    [
    ];
  }
}


###Relational
Database my::db
(
  Table PersonTable
  (
    NAME CHAR(200),
    FIRMID INTEGER
  )
  Table FirmTable
  (
    FIRMNAME CHAR(200),
    ID INTEGER
  )

  Join Firm_Person(PersonTable.FIRMID = FirmTable.ID)
)


###Pure
Class <<temporal.businesstemporal>> my::Person
{
  name: String[1];
  firmID: Integer[1];
}

Class my::Firm
{
  legalName: String[1];
  id: Integer[1];
}


###Mapping
Mapping my::map
(
  *my::Person: Pure
  {
  }
)
```
