### ISSUE TITLE
Bug: Issue with conflict resolution abort flow

### ISSUE THREAD

**Issue by umarphaarook** [finos/legend-studio#644]
### Similar issues

- [X] I have searched and found no existing similar issues

### How are you using Studio?

Legend Studio

### Current and expected behavior

Conflict resolution flow aims at helping users to resolve conflicts in their code if they ever occur. Users could either proceed on the resolution process until all conflicts were resolved or abort midway and revert back to a clean state prior to the conflict occurrence. Below is a brief summary of the expected result versus the actual result:
- The expectation is, when the user is in a conflict resolution process and abort, they should be transitioned back to the edit layout so that they can save and update to revert back to a clean state.
- But the actual result is, after the conflict resolution process is aborted, back in the edit layout, clicking the update button transitions users back to the conflict resolution layout (even though there are no conflicts to be resolved).
 

### Steps to reproduce

To reproduce the bug, follow the steps in this [conflict-resolution-test-script](https://github.com/finos/legend-studio/blob/master/packages/legend-manual-tests/cypress/script-docs/conflict-resolution.md), the problem occurs at [**TEST 3**](https://github.com/finos/legend-studio/blob/master/packages/legend-manual-tests/cypress/script-docs/conflict-resolution.md#test3-conflict) step

### Environment

```text
System:
  OS: macOS 11.4
Browsers:
  Chrome: 95.0.4638
Binaries:
  Node: 14.17.1
  Yarn: 1.22.10
  npm: 6.14.13
```

### Contribution

- [ ] I would like to work on the fix for this issue

**Comment by akphi** [comment]
This should be closed by https://github.com/finos/legend-studio/pull/749
