### ISSUE TITLE
Bug: Fail to expand attributes of a class in the query builder if it is mapped using Inline embedded property mapping

### ISSUE THREAD

**Issue by YannanGao-gs** [finos/legend-studio#650]
### Similar issues

- [X] I have searched and found no existing similar issues

### How are you using Studio?

Legend Query

### Current and expected behavior

What happened:
Fail to expand attributes of a class in the query builder if it is mapped using Inline embedded property mapping

https://user-images.githubusercontent.com/73408381/140529637-30881d8c-ab37-4715-a8ec-1e4638f73539.mov

Expected: 
Display the attributes of the class  (e.g. firm in the demo video)

### Steps to reproduce

- Copy the model below and paste it in the text mode
- Switch to form mode and open the relationalMapping e.g. simpleRelationalMapping for the below model
- Create a MappingTest based on 'Person'
- Open the query builder 
- Click the Firm to display its attributes 

https://user-images.githubusercontent.com/73408381/140530387-fdbc1bc2-818c-456e-ae90-ab4bb07b9f94.mov

### Model data

```text
###Relational
Database Oct::stores::ParentStore
(
  include Oct::stores::ChildStore

  Table FIRMTABLE
  (
    ID INTEGER,
    NAME VARCHAR(10)
  )

  Join FRIM_PERSON(FIRMTABLE.ID = PERSONTABLE.FIRMID)
  Join FRIM_CEO(FIRMTABLE.ID = PERSONTABLE.FIRMID)
)

Database Oct::stores::ChildStore
(
  Table PERSONTABLE
  (
    ID INTEGER,
    NAME VARCHAR(10),
    FIRMID INTEGER
  )
)


###Pure
Class Oct::models::Person
{
  lName: String[1];
  fName: String[1];
  firm: Oct::models::Firm[1];
}

Class Oct::models::Firm
{
  id: Integer[1];
  name: String[1];
  employees: Oct::models::Person[*];
}


###Mapping
Mapping Oct::mappings::simpleRelationalMapping
(
  *Oct::models::Firm[testInlineMapping]: Relational
  {
    ~mainTable [Oct::stores::ParentStore]FIRMTABLE
    id: [Oct::stores::ParentStore]FIRMTABLE.ID,
    name: [Oct::stores::ParentStore]FIRMTABLE.NAME
  }
  *Oct::models::Person: Relational
  {
    ~mainTable [Oct::stores::ParentStore]PERSONTABLE
    fName: [Oct::stores::ChildStore]PERSONTABLE.NAME,
    firm() Inline[testInlineMapping]
  }
)
```

### Environment

```text
System:
    OS: macOS 12.0.1
  Binaries:
    Node: 16.10.0 - /private/var/folders/7l/8nlbhlj55c9_lp8c23_61n8h0000gn/T/xfs-ac754eb3/node
    Yarn: 3.0.1 - /private/var/folders/7l/8nlbhlj55c9_lp8c23_61n8h0000gn/T/xfs-ac754eb3/yarn
    npm: 7.24.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 95.0.4638.69
```

### Contribution

- [ ] I would like to work on the fix for this issue

**Comment by akphi** [comment]
Thanks for filing the issue! This has more to do with the generic `Query Builder` instead of `Legend Query` app so I'll relabel them.
