### ISSUE TITLE
Bug: Enum Mapping info lost on switching between form and text mode 

### ISSUE THREAD

**Issue by hardikmaheshwari** [finos/legend-studio#658]
### Similar issues

- [X] I have searched and found no existing similar issues

### How are you using Studio?

Legend Studio

### Current and expected behavior

Current : If we copy-paste the attached grammar and toggle between form mode & text mode we loose Enumeration Mapping attached with property mapping and compilation fails as expected
Expected : Toggling between form mode & text mode should not affect the grammar

### Steps to reproduce

Copy the attached grammar in studio workspace & toggle between form & text mode. Compilation fails after toggle

### Model data

```text
###Pure
Enum demo::TestEnum
{
  Value1
}

Class demo::TestClass
{
  testEnum: demo::TestEnum[1];
}

Class demo::S_testClass
{
  testEnum: String[1];
}


###Mapping
Mapping demo::TestEnumMapping
(
  demo::TestEnum: EnumerationMapping
  {
    Value1: ['value1']
  }
  demo::TestEnum: EnumerationMapping testEnumMapping1
  {
    Value1: ['value1']
  }
)

Mapping demo::TestMapping
(
  include demo::TestEnumMapping

  *demo::TestClass: Pure
  {
    ~src demo::S_testClass
    testEnum: EnumerationMapping demo_TestEnum:  $src.testEnum
  }
  demo::TestClass[testClassMapping1]: Pure
  {
    ~src demo::S_testClass
    testEnum: EnumerationMapping testEnumMapping1: $src.testEnum
  }
  demo::TestClass[testClassMapping2]: Pure
  {
    ~src demo::S_testClass
    testEnum: EnumerationMapping testEnumMapping2: $src.testEnum
  }

  demo::TestEnum: EnumerationMapping testEnumMapping2
  {
    Value1: ['value1']
  }
)

```

### Environment

```text
System:
    OS: windows 10
  Browsers:
    Chrome: 95.0.4638.69
```

### Contribution

- [x] I would like to work on the fix for this issue

**Comment by hardikmaheshwari** [comment]
> @hardikmaheshwari Does this pass the grammar roundtrip in engine?

Yes it does. Also a bit of investigation that I did in case its helpful
 - We start from text mode with this grammar. Compilation succeeds
 - Toggle to Form mode
    - When we pass the grammar to transformGrammarToJsonApi, we have this field - `"enumMappingId": "demo_TestEnum",`
 - Compile in Form Mode
    - When we pass the json to transformJsonToGrammarApi this field is missing

**Comment by akphi** [comment]
@hardikmaheshwari gotcha. Also, we should probably file bug in engine for not catching this at compile time. Duplicated enum values and duplicated class properties.

Studio probably would hard fail this at graph builder step.

**Comment by hardikmaheshwari** [comment]
@akphi yes that's a good observation. I'll do that

**Comment by MauricioUyaguari** [comment]
Updated the grammar. The issue is unrelated to the duplicate enums. We should file an issue with engine to do these via compilation checks for both duplicate property names and duplicate enum values. Pure right now has this validation.

**Comment by hardikmaheshwari** [comment]
> Updated the grammar. The issue is unrelated to the duplicate enums. We should file an issue with engine to do these via compilation checks for both duplicate property names and duplicate enum values. Pure right now has this validation.

Thanks @MauricioUyaguari . Yes I'll do that but just to clarify issue that I am reporting here is not related to duplicated values
but on togling between form and text mode we are lossing info about EnumerationMapping
`testEnum: EnumerationMapping demo_TestEnum : $src.testEnum`

gets changed to

`testEnum: $src.testEnum`

**Comment by MauricioUyaguari** [comment]
@hardikmaheshwari Yes, that is correct.
