### ISSUE TITLE
Feature request:  Handle processing of milestoning classes 

### ISSUE THREAD

**Issue by YannanGao-gs** [finos/legend-studio#683]
### Similar issues

- [X] I have searched and found no existing similar issues

### How are you using Studio?

Legend Studio

### Current and expected behavior

The model below should work well in the Studio

### Steps to reproduce

use the below model

### Model data

```text
###Relational
Database my::db
(
  Table PersonTable
  (
    NAME CHAR(200),
    FIRMID INTEGER
  )
  Table FirmTable
  (
    FIRMNAME CHAR(200),
    ID INTEGER
  )

  Join Firm_Person(PersonTable.FIRMID = FirmTable.ID)
)


###Pure
Class <<temporal.businesstemporal>> my::Person
{
  name: String[1];
  firmID: Integer[1];
}

Class my::Firm
{
  legalName: String[1];
  id: Integer[1];
}

Association my::Employment
{
  firm: my::Firm[0..1];
  employees: my::Person[*];
}


###Mapping
Mapping my::map
(
  my::Person[per1]: Relational
  {
    ~mainTable [my::db]PersonTable
    name: [my::db]PersonTable.NAME
  }
  my::Firm[fir1]: Relational
  {
    ~mainTable [my::db]FirmTable
    legalName: [my::db]FirmTable.FIRMNAME
  }

  my::Employment: Relational
  {
    AssociationMapping
    (
      employeesAllVersions[fir1,per1]: [my::db]@Firm_Person,
      firm[per1,fir1]: [my::db]@Firm_Person
    )
  }
)
```

### Environment

```text
System:
    OS: macOS 12.0.1
  Binaries:
    Node: 16.10.0 - /private/var/folders/7l/8nlbhlj55c9_lp8c23_61n8h0000gn/T/xfs-ac754eb3/node
    Yarn: 3.0.1 - /private/var/folders/7l/8nlbhlj55c9_lp8c23_61n8h0000gn/T/xfs-ac754eb3/yarn
    npm: 7.24.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 95.0.4638.69
```

### Contribution

- [X] I would like to work on the fix for this issue

**Comment by MauricioUyaguari** [comment]
Moving this to backlog as Mapping defined above is incorrect. Users should not be allowed to map the `allVersion` property in a mapping. 
If there is a requirement for studio to generate milestoning properties we will look to implement this.

**Comment by akphi** [comment]
@MauricioUyaguari @YannanGao-gs Could we update the name of this issue to something more specific. The title now suggests support milestoning in general, which is confusing 😢

**Comment by gayathrir11** [comment]
### Describe the solution you would like to see implemented

Generate `DerivedProperty` which takes `Date` as an input, `allVersions` property and `allVersionsInRange` derived property for all the milestoned properties in classes and associations. Refer https://github.com/finos/legend-engine/blob/master/legend-engine-language-pure-compiler/src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/Milestoning.java

**Comment by akphi** [comment]
I'll close this for now as the description does not make a lot of sense to me and also we're about to file a new issue for milestoning for supporting `allVersions`, `inRange`, and friends.
