### ISSUE TITLE
Iteration Plan for Version 2.0.0 (Nov 2021)

### ISSUE THREAD

**Issue by akphi** [finos/legend-studio#684]
In this milestone, we focus on stabilizing Studio editor, introducing new features to query builder, as well as solidifying the usage of `dataspace`. 

(TODO)

### Editor

- [Bug: Issue with DnD from relational mapping table source tree for joins](https://github.com/finos/legend-studio/issues/651)

### Query Builder

- [Bug: Value Specification Collection Editor Only handles String ](https://github.com/finos/legend-studio/issues/564)
- [Bug: Query builder roundtrip fails when we have a derived property in graph-fetch](https://github.com/finos/legend-studio/issues/428)
- [Feature Request: do validation on query projection columns with duplicated names](https://github.com/finos/legend-studio/issues/626)
- [Feature Request: support derivation as LHS for filter](https://github.com/finos/legend-studio/issues/627)
- [Feature Request: support more date/time capabilities in query filter](https://github.com/finos/legend-studio/issues/628)
- [Feature request: Handle subtypes in query builder](https://github.com/finos/legend-studio/issues/630)
- [Bug: Unable to open query builder form editor for multiply Boolean expression of an explosion property](https://github.com/finos/legend-studio/issues/648)

### Integration

- [Feature request: Add support for querying a versioned class (i.e. milestoned)](https://github.com/finos/legend-studio/issues/619)
- [Feature request: Handle processing of milestoning classes](https://github.com/finos/legend-studio/issues/683)
- [Feature request: Stand-alone enterprise model explorer (MVP)](https://github.com/finos/legend-studio/issues/664)
- [Add extension support for external language Morphir](https://github.com/finos/legend-studio/pull/640)
- [Feature request: Properly handle duplicated attributes (in enumerations, classes, associations, profiles...)](https://github.com/finos/legend-studio/issues/660)

**Comment by YannanGao-gs** [comment]
Editor

- [Bug: Issue with DnD from relational mapping table source tree for joins](https://github.com/finos/legend-studio/issues/651)

Query Builder

- [Bug: Value Specification Collection Editor Only handles String ](https://github.com/finos/legend-studio/issues/564)
- [Bug: Query builder roundtrip fails when we have a derived property in graph-fetch](https://github.com/finos/legend-studio/issues/428)
- [Feature Request: do validation on query projection columns with duplicated names](https://github.com/finos/legend-studio/issues/626)
- [Feature Request: support derivation as LHS for filter](https://github.com/finos/legend-studio/issues/627)
- [Feature Request: support more date/time capabilities in query filter](https://github.com/finos/legend-studio/issues/628)
- [Feature request: Handle subtypes in query builder](https://github.com/finos/legend-studio/issues/630)
- [Bug: Unable to open query builder form editor for multiply Boolean expression of an explosion property](https://github.com/finos/legend-studio/issues/648)
- 

Integration

- [Feature request: Add support for querying a versioned class (i.e. milestoned)](https://github.com/finos/legend-studio/issues/619)
- [Feature request: Handle processing of milestoning classes](https://github.com/finos/legend-studio/issues/683)
- [Feature request: Stand-alone enterprise model explorer (MVP)](https://github.com/finos/legend-studio/issues/664)
- [Add extension support for external language Morphir](https://github.com/finos/legend-studio/pull/640)
- [Feature request: Properly handle duplicated attributes (in enumerations, classes, associations, profiles...)](https://github.com/finos/legend-studio/issues/660)
