### ISSUE TITLE
Feature request: Project Access Roles for Users

### ISSUE THREAD

**Issue by MauricioUyaguari** [finos/legend-studio#750]
### Similar requests

- [X] I have searched and found no existing similar requests

### What problems are you trying to solve?

Users should be able to see their access roles for a given project and request access. Additionally 'MAINTAINER' should be able to approve/deny access roles requests. 

### Describe the solution you would like to see implemented

1. `legend-sdlc` 
   - [ ] `Api` View Access roles. https://legend.finos.org/sdlc/api/swagger#/Projects/getProjectAccessRole
   - [ ] `Api` Request Access Roles
   - [ ] `Api` Approve/Deny Access Roles
2. Add to `Project Overview` Panel
   - [ ] Show Access Roles
   - [ ] Editor to request/approve/deny  

Documentation on gitlab access requests: https://docs.gitlab.com/ee/api/access_requests.html

### Documentation, Design, Adoption, Migration Strategy

https://docs.gitlab.com/ee/api/access_requests.html

### Contribution

- [ ] I would like to work on this feature

**Comment by akphi** [comment]
I will close for now. I don't think we should directly deal with `access role` coming from `Gitlab`, until `SDLC` provides an abstraction around access role, we should not make use of them.
