### ISSUE TITLE
Feature request: Support updating out of sync workspaces including Conflict Resolution

### ISSUE THREAD

**Issue by MauricioUyaguari** [finos/legend-studio#756]
### Similar requests

- [X] I have searched and found no existing similar requests

### How are you using Studio?

Legend Studio

### What problems are you trying to solve?

Provide an interface to users to handle local conflicts in changes. 
For now this can occur in two situations
- User current workspace revision is outdated with the head of workspace. Conflicts resulted in local changes vs base/head of workspace. 
- User apply patches and conflicts results from patch changes and local changes.

### Describe the solution you would like to see implemented

- Workspace conflict 
  - [x] Provide user notification when workspace is not in sync with head revision. i.e when saving, local change viewer
- Main Conflict Resolution
  - [x] Compute the diff between the base revision and the current revision
  - [x] Compute conflicts between the 2 sets of changes
  - [x] Create an interface (similar to conflict resolution) to resolve the conflict, in the end, we end up with changes in the workspace. Bug detected https://github.com/finos/legend-studio/issues/814

### Contribution

- [X] I would like to work on this feature

**Comment by akphi** [comment]
Discussed with the highly sought-after @MauricioUyaguari and the decision is to leave `model loader` out of this. Model loader operation is imperative and will override anything as well as do a hard reload on the graph, there's no safety, conflict check we would need to do, but if we do `hard save` like in https://github.com/finos/legend-studio/issues/191, we would probably need to do some safety check.
