### ISSUE TITLE
Feature request: Enhance Viewer Mode

### ISSUE THREAD

**Issue by MauricioUyaguari** [finos/legend-studio#779]
### Similar requests

- [X] I have searched and found no existing similar requests

### What problems are you trying to solve?

Right now viewer mode lacks certain functionality available in edit mode that is not editor specific. We should add these features to viewer mode where possible. 

### Describe the solution you would like to see implemented

- [x] Add Project Overview to alloy users to do the following via viewer mode
    - edit project description, tag
    - view/delete workspaces in the project
    - view versions of the project
    - create a release for the project
- [x]  Workspace Workflow to see workjobs in the project. 
-  Review - Might make sense to implement a review side bar specific to viewer mode to see and open all reviews in the project. Moving to https://github.com/finos/legend-studio/issues/813

### Contribution

- [X] I would like to work on this feature

**Comment by akphi** [comment]
I think it's time to do this https://github.com/finos/legend-studio/issues/317
