### ISSUE TITLE
Feature request: Add function explorer panel in Query Builder for user defined functions

### ISSUE THREAD

**Issue by YannanGao-gs** [finos/legend-studio#819]
### Similar requests

- [X] I have searched and found no existing similar requests

### How are you using Studio?

Legend Studio

### What problems are you trying to solve?

To enhance our user experience in using user-defined functions in the query builder. 
Adding a function explorer panel would give users ability to explorer functions defined in the project and drag and drop into fetch structure panel. 

### Implementation Ideas/Steps
- [x] Enable a new panel for user-defined functions 
- [x] Two modes of displaying by package or flatten out by function name
- [x] `CONSIDER` Leverage the `doc.doc` tag value so producers of function can add documentation for the function and consumers can read tag value and learn what function does
- [x] For functions whom return type is primitive users can DND directly into fetch structure. 
- [x] Drag and drop into derivation panel 
- [ ] `CONSIDER` include on the fly `calculated attributes` where users can reuse defined attributes within query builder: @akphi - I have thought about this and I think we can support it but it doesn't have to persistable, meaning that within one editing session, the user can create their calculated attribute to save time, then DnD it etc. but this will not exist in the next editing session (I have seen this behavior in Google Sheets before with number format)
- [x] `CONSIDER` add a dropdown somewhere to enable/disable panels to show as we start to have too many panels (parameters, setup, explorer, functions, calculated attributes, etc.)

**Comment by akphi** [comment]
I have updated the list a bit to add my own refinement to the implementation plan
