### ISSUE TITLE
Update font colors in Studio Diagram

### ISSUE THREAD

**Issue by njerigrevious** [finos/legend-studio#825]
### Similar requests

- [X] I have searched and found no existing similar requests

### How are you using Studio?

Legend Studio

### What problems are you trying to solve?
It is hard to see with white on gray particularly when I am presenting or take a screenshot. 

### Describe the solution you would like to see implemented

Explore darker font color on gray background in studio diagram view

### Contribution

- [ ] I would like to work on this feature

**Comment by akphi** [comment]
This should be taken care of as part of #264
