### ISSUE TITLE
Feature request: Enhance mapping algorithm to incorporate operational class mapping and subtype

### ISSUE THREAD

**Issue by YannanGao-gs** [finos/legend-studio#834]
### Similar requests

- [X] I have searched and found no existing similar requests

### How are you using Studio?

Legend Studio, Legend Query

### What problems are you trying to solve?

When considering if a property is mapped or not, the mapping algorithm could become more complicated if there are subtype and operational class mappings such as union..
Ideally, all mapped properties should be displayed in the explorer tree for further operations.

### Describe the solution you would like to see implemented

- [ ] Consider property ownership for subtype in the context of mapping https://github.com/finos/legend-studio/pull/812
- [ ] Incorporate different types of operational class mappings
 

### Contribution

- [ ] I would like to work on this feature

**Comment by akphi** [comment]
@MauricioUyaguari @YannanGao-gs I believe we either split this or rename this issue since `subtyping` and `operational class mappings` are 2 separate factors
