### ISSUE TITLE
Feature request: Post Filter in Query Editor

### ISSUE THREAD

**Issue by njerigrevious** [finos/legend-studio#839]
### Similar requests

- [X] I have searched and found no existing similar requests

### How are you using Studio?

Legend Query

### What problems are you trying to solve?

Many users have requested the ability to perform a post-filter rather than a regular filter in Query. Post filters allow you to perform filter operations on the Tabular Data Structure `TDS` structure returned by the `project` function. 

### Describe the solution you would like to see implemented

- [x] Add `TDSRow` class to graph
- [x] Add value specification processing of `filter` on projection
- [x] Add query builder processing on `filter` on projection
- [x] Add lambda builder processing on `filter` on projection
- [x] FORM MODE
    - [x] add post filter panel
    - [x] add support for hiding/showing panel. default should hide
    - [x] DND for projection columns
      - [x] `disable` for graph fetch
      - [x] auto generate filter lambda based on column
      - [x] handle derivation columns (should use [engine ](https://github.com/finos/legend-engine) return type api to generate correct post filter lambda)
      - [x] enable group filter just like in regular filter

  

### Sample Query to Support
```
|model::Person.all()->project(
  [
    x|$x.firstName,
    x|$x.lastName
  ],
  [
    'First Name',
    'Last Name'
  ]
)->filter(
  row|$row.getString('First Name') == 'John'
)
```

**Comment by akphi** [comment]
@njerigrevious the correct label to use for this is `Component: Query Builder`, not `Application: Query` since this refers to the shared part that even `Studio` can use. Please note that next time. Thanks!!
