### ISSUE TITLE
Bug: DateTime value specification editor produces StrictDate type causing class cast exception

### ISSUE THREAD

**Issue by MauricioUyaguari** [finos/legend-studio#842]
### Similar issues

- [X] I have searched and found no existing similar issues

### How are you using Studio?

Legend Studio

### Current and expected behavior

A property of type `DateTime` should produce a text input for users to type out the dateTime. This is both for filter and parameter instance editor
Currently we show a `StrictDate` value editor for properties of `DateTime`. This causes a class exception when executing. 

### Environment

```text
Chrome
```

### Contribution

- [ ] I would like to work on the fix for this issue

**Comment by akphi** [comment]
@MauricioUyaguari could you rename the issue?
