### ISSUE TITLE
Embed clickable icons to navigate to docs both in form and text mode

### ISSUE THREAD

**Issue by njerigrevious** [finos/legend-studio#864]
### Similar requests

- [X] I have searched and found no existing similar requests

### How are you using Studio?

Legend Studio

### What problems are you trying to solve?

Users should be able to navigate to product docs directly from the UI. Product docs should be hosted externally to make them available for both internal and external users.

### Describe the solution you would like to see implemented
- [ ] Add `docUrl` to `appConfig`
  - [ ] Create new workspace dialog (title) - url: https://legend.finos.org/docs/studio/create-workspace
  - [ ] (?) Create a class (title bar right side) - url: https://legend.finos.org/docs/studio/create-data-model#define-a-new-class **(also do this for enumeration, etc.)**
  - [ ] (?) Create a diagram (same as class) - url: https://legend.finos.org/docs/studio/create-diagram
  - [ ] (?) Create mapping ...
  - [ ] (?) Create service ...
  - [ ] (?) Create connection editor
- [ ] `discuss` text mode
  - [ ] `investigate` adding helper context in text mode `monaco-editor` to provide clickable link after user types packagble elements. Example: user types `###Service`, show context helper linking to service docs when [hover over](https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-hover-provider-example) the text, and when people are [typing](https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-completion-provider-example), i.e. autocomplete
  - [ ] `idea` add similar docs for lambda
  - [ ] `maybe` build helper context for lambdas to show how to write specific functions such as `if` statements.

**Comment by akphi** [comment]
As discussed, the strategy for doc going forward would be to localize them. For example, we focus on `home page` like in https://github.com/finos/legend-studio/issues/904 or we on `connection editor` like in https://github.com/finos/legend-studio/issues/259

As for now, we will split this PR into #903 and #904
