### ISSUE TITLE
Feature request: Add global test runner

### ISSUE THREAD

**Issue by MauricioUyaguari** [finos/legend-studio#865]
### Similar requests

- [X] I have searched and found no existing similar requests

### How are you using Studio?

Legend Studio

### What problems are you trying to solve?

Currently we have a few elements that have tests associated with them (Mapping, Service). We run those tests directly on the editor. However there is no way to globally run all tests in the project. This would help catch build failure and give awareness to the user of what tests and where are failing. 

### Describe the solution you would like to see implemented

Ideas
- [ ] Provide `Test` Activity Panel
- [ ] show all tests in the project
- [ ] global run as well as individual runs
- [ ] on failure open relevant editor to address test 

### Contribution

- [ ] I would like to work on this feature

**Comment by akphi** [comment]
Should be closed by https://github.com/finos/legend-studio/pull/1114 https://github.com/finos/legend-studio/pull/1229 and https://github.com/finos/legend-studio/pull/1224

Though as @MauricioUyaguari said, this is still in `WIP` status, but I believe we can close this issue now.

**Comment by MauricioUyaguari** [comment]
Closed by  https://github.com/finos/legend-studio/pull/1114
