### ISSUE TITLE
Feature request: Show a link to go to Gitlab project

### ISSUE THREAD

**Issue by akphi** [finos/legend-studio#905]
### Similar requests

- [X] I have searched and found no existing similar requests

### How are you using Studio?

Legend Studio

### What problems are you trying to solve?

It would be convenient to be able to navigate to the underlying VSC service (i.e. `Gitlab`) for a particular project.

### Describe the solution you would like to see implemented

- [x] Return `webUrl` for a project in SDLC - https://github.com/finos/legend-sdlc/pull/380
- [x] Update `studio` to show this link somewhere (consider `review`, `viewer` and `editor` modes)

### Contribution

- [X] I would like to work on this feature

**Comment by akphi** [comment]
The change in Studio is done, but the feature would not work until we release `sdlc`. So moved this to `5.0.0`

**Comment by beekemarie** [comment]
@akphi - are we releasing this feature with 5.0.0? Are SDLC changes live? Could you please also add a screenshot to this issue showing where users can find the link?

**Comment by akphi** [comment]
Yeah, we have already included the video in the PR that closes this issue - see https://github.com/finos/legend-studio/pull/910
