### ISSUE TITLE
Enhancement: remove graph building in text mode to improve performance

### ISSUE THREAD

**Issue by MauricioUyaguari** [finos/legend-studio#966]
c### Similar requests

- [X] I have searched and found no existing similar requests

### How are you using Studio?

Legend Studio

### What problems are you trying to solve?

In order to improve performance in text mode, we could consider removing `Studio` graph building during text mode. 

### Describe the solution you would like to see implemented

Currently, we rebuild our graph during each compilation. We will move to rebuild only when leaving text mode. 

- [ ] remove logic of rebuilding when firing `F9` in text-mode
- [ ] handle explorer tree logic which requires graph: we can reason out the explorer tree from just the element paths
- [ ] handle change detection (show that we disabled change detection in text mode and prevent users from saving, or we could use another change detection mode - `maybe` compare hashes index built from protocol models)
- [ ] Move from a soft transition from/to text mode to a hard transition. Right now we try to keep the form mode state of studio in memory when going to text mode. we should delete that and only rebuild when going back to form mode - we currently already somewhat doing this, but we haven't pushed this hard enough, this would really help avoiding memory-leak: genericize `EditorStore` and implement `TextEditorStore`, `FormEditorStore` to further separate these out (See #317 )
  - [ ] `?` would remove the `reprocessElementEditorState`

### Contribution

- [ ] I would like to work on this feature

**Comment by gayathrir11** [comment]
- [ ] Update the graph for `testables`
- [ ] Make sure UI does not break when we click on the new elements added in the Local changes tab
