### ISSUE TITLE
Optimize Legend Query Setup for Create New Queries and Queries from Services

### ISSUE THREAD

**Issue by MauricioUyaguari** [finos/legend-studio#967]
### Similar requests

- [X] I have searched and found no existing similar requests

### How are you using Studio?

Legend Query

### What problems are you trying to solve?

Improve the user experience during the setup in `Legend Query` when selecting mapping/runtime. 

### Describe the solution you would like to see implemented

Simplify runtime/mapping pair analytics by not building the whole graph and showing users only runtime/mapping pairs. 

- add `Bare_Mapping`, `Bare_Runtime`.
- calculate runtime selectors based on mappings.

### Contribution

- [ ] I would like to work on this feature

**Comment by akphi** [comment]
Fixed by https://github.com/finos/legend-studio/pull/983
